# Generated by Django 2.2.7 on 2019-11-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=13, help_text='Longitude', max_digits=100)),
                ('Longitude', models.DecimalField(decimal_places=13, help_text='Latitude', max_digits=100)),
                ('Unique_Squirrel_ID', models.CharField(help_text='ID of squirrel', max_length=100)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], max_length=100)),
                ('Date', models.DateField(help_text='Date')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Other', 'Other')], default='Other', help_text='Age', max_length=100)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Other', 'Other')], default='Other', max_length=100)),
                ('Location', models.CharField(choices=[('Ground_Plane', 'Ground_Plane'), ('Above_Ground', 'Above_Ground'), ('Other', 'Other')], default='Other', max_length=100)),
                ('Specific_Location', models.CharField(default=None, max_length=100)),
                ('Running', models.BooleanField(default=False)),
                ('Chasing', models.BooleanField(default=False)),
                ('Climbing', models.BooleanField(default=False)),
                ('Eating', models.BooleanField(default=False)),
                ('Foraging', models.BooleanField(default=False)),
                ('Other_Activities', models.CharField(max_length=100)),
                ('Kuks', models.BooleanField(default=False)),
                ('Quaas', models.BooleanField(default=False)),
                ('Moans', models.BooleanField(default=False)),
                ('Tail_flags', models.BooleanField(default=False)),
                ('Tail_twitches', models.BooleanField(default=False)),
                ('Approaches', models.BooleanField(default=False)),
                ('Indifferent', models.BooleanField(default=False)),
                ('Runs_from', models.BooleanField(default=False)),
            ],
        ),
    ]
