# Generated by Django 2.2.7 on 2019-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Other_Activities',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='PM', max_length=100),
        ),
    ]
