# Generated by Django 2.2.7 on 2019-12-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191206_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Other', 'Other')], default='Other', help_text='Age', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Date',
            field=models.DateField(blank=True, help_text='Date', null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground_Plane', 'Ground_Plane'), ('Above_Ground', 'Above_Ground'), ('Other', 'Other')], default='Other', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Other_Activities',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Other', 'Other')], default='Other', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Specific_Location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
