# Generated by Django 2.2.7 on 2019-12-06 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191206_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date', null=True),
        ),
    ]
