# Generated by Django 2.2.7 on 2019-12-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20191206_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Date',
            field=models.DateField(blank=True, default='9999-12-31', help_text='Date', null=True),
        ),
    ]
